{"name": "test_employee_attrs_negative", "status": "failed", "statusDetails": {"message": "AssertionError: [Desired user's attrs are equal to desired dict of attrs] Expected <{.., 'team_size': 5}> to be equal to <{.., 'team_size': 7}>, but was not.", "trace": "self = <Lesson_30.test_employee.TestEmployee object at 0x103b60bc0>\n\n    def test_employee_attrs_negative(self):\n        (assert_that(self.qa_automation_team_lead.__dict__,\n                     \"Desired user's attrs are equal to desired dict of attrs\")\n>        .is_equal_to(self.failed_mark_attrs))\nE       AssertionError: [Desired user's attrs are equal to desired dict of attrs] Expected <{.., 'team_size': 5}> to be equal to <{.., 'team_size': 7}>, but was not.\n\ntest_employee.py:31: AssertionError"}, "start": 1730379039825, "stop": 1730379039825, "uuid": "4f9c0c71-724f-4ea2-bc65-c52d2138a611", "historyId": "bdb622a7ceef6a74cb7b3b4ff0bc43ce", "testCaseId": "bdb622a7ceef6a74cb7b3b4ff0bc43ce", "fullName": "test_employee.TestEmployee#test_employee_attrs_negative", "labels": [{"name": "suite", "value": "test_employee"}, {"name": "subSuite", "value": "TestEmployee"}, {"name": "host", "value": "Air-Sergij"}, {"name": "thread", "value": "95183-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_employee"}]}