{"name": "Negative Test for Employee Attributes", "status": "failed", "statusDetails": {"message": "AssertionError: [Desired user's attrs are equal to desired dict of attrs] Expected <{.., 'team_size': 5}> to be equal to <{.., 'team_size': 7}>, but was not.", "trace": "self = <Lesson_30.test_employee.TestEmployee object at 0x103b9b3e0>\n\n    @allure.story('Test Allure')\n    @allure.title('Negative Test for Employee Attributes')\n    def test_employee_attrs_negative(self):\n        with allure.step(\"Starting negative test for employee attributes\"):\n            logger.info(\"Starting negative test for employee attributes\")\n    \n            allure.attach(str(self.failed_mark_attrs), name=\"Expected Attributes\",\n                          attachment_type=allure.attachment_type.TEXT)\n            allure.attach(str(self.qa_automation_team_lead.__dict__), name=\"Actual Attributes\",\n                          attachment_type=allure.attachment_type.TEXT)\n    \n            logger.info(\"Comparing actual attributes with expected attributes\")\n            assert_that(self.qa_automation_team_lead.__dict__,\n>                       \"Desired user's attrs are equal to desired dict of attrs\").is_equal_to(self.failed_mark_attrs)\nE           AssertionError: [Desired user's attrs are equal to desired dict of attrs] Expected <{.., 'team_size': 5}> to be equal to <{.., 'team_size': 7}>, but was not.\n\ntest_employee.py:58: AssertionError"}, "steps": [{"name": "Starting negative test for employee attributes", "status": "failed", "statusDetails": {"message": "AssertionError: [Desired user's attrs are equal to desired dict of attrs] Expected <{.., 'team_size': 5}> to be equal to <{.., 'team_size': 7}>, but was not.\n", "trace": "  File \"/Users/serhii.ravliuk/PycharmProjects/Lesson_2_1/Lesson_30/test_employee.py\", line 58, in test_employee_attrs_negative\n    \"Desired user's attrs are equal to desired dict of attrs\").is_equal_to(self.failed_mark_attrs)\n                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/serhii.ravliuk/PycharmProjects/Lesson_2_1/.venv/lib/python3.12/site-packages/assertpy/base.py\", line 123, in is_equal_to\n    self._dict_err(self.val, other, ignore=kwargs.get('ignore'), include=kwargs.get('include'))\n  File \"/Users/serhii.ravliuk/PycharmProjects/Lesson_2_1/.venv/lib/python3.12/site-packages/assertpy/helpers.py\", line 245, in _dict_err\n    self.error('Expected <%s> to be equal to <%s>%s%s, but was not.' % (\n  File \"/Users/serhii.ravliuk/PycharmProjects/Lesson_2_1/.venv/lib/python3.12/site-packages/assertpy/assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "attachments": [{"name": "Expected Attributes", "source": "f0a9dcc8-6b10-46da-b7b3-e27ad645504b-attachment.txt", "type": "text/plain"}, {"name": "Actual Attributes", "source": "9eb1e2eb-8af1-40ca-a403-1ad1c03951cf-attachment.txt", "type": "text/plain"}], "start": 1730380165162, "stop": 1730380165163}], "start": 1730380165162, "stop": 1730380165164, "uuid": "619d4277-cef5-4b97-abfc-7c8a2b0b880e", "historyId": "bdb622a7ceef6a74cb7b3b4ff0bc43ce", "testCaseId": "bdb622a7ceef6a74cb7b3b4ff0bc43ce", "fullName": "test_employee.TestEmployee#test_employee_attrs_negative", "labels": [{"name": "story", "value": "Test Allure"}, {"name": "suite", "value": "test_employee"}, {"name": "subSuite", "value": "TestEmployee"}, {"name": "host", "value": "Air-Sergij"}, {"name": "thread", "value": "95585-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_employee"}]}